<a href="https://colab.research.google.com/github/ndb796/Python-Data-Analysis-and-Image-Processing-Tutorial/blob/master/05.%20Numpy%EC%9D%98%20%ED%99%9C%EC%9A%A9/Numpy%EC%9D%98%20%ED%99%9C%EC%9A%A9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Numpy의 활용
[강의 노트](https://github.com/ndb796/Python-Data-Analysis-and-Image-Processing-Tutorial/blob/master/05.%20Numpy%EC%9D%98%20%ED%99%9C%EC%9A%A9/Python%20%EB%8D%B0%EC%9D%B4%ED%84%B0%20%EB%B6%84%EC%84%9D%EA%B3%BC%20%EC%9D%B4%EB%AF%B8%EC%A7%80%20%EC%B2%98%EB%A6%AC%20-%20Numpy%EC%9D%98%20%ED%99%9C%EC%9A%A9.pdf)

Python의 Numpy는 **저장 및 불러오기**가 가능합니다.

In [1]:
import numpy as np

# 단일 객체 저장 및 불러오기
array = np.arange(0, 10)
np.save('saved.npy', array)

result = np.load('saved.npy')
print(result)

[0 1 2 3 4 5 6 7 8 9]


여러 개의 Numpy의 객체를 하나의 파일에 저장하고 불러올 수 있습니다.

In [3]:
import numpy as np

# 복수 객체 저장 및 불러오기
array1 = np.arange(0, 10)
array2 = np.arange(10, 20)
np.savez('saved.npz', array1=array1, array2=array2)

data = np.load('saved.npz')
result1 = data['array1']
result2 = data['array2']
print(result1)
print(result2)

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]


Numpy의 원소들은 특정한 기준에 따라서 **정렬**할 수 있습니다.

In [4]:
import numpy as np

# Numpy 원소 오름차순 정렬
array = np.array([5, 9, 10, 3, 1])
array.sort()
print(array)

# Numpy 원소 내림차순 정렬
array = np.array([5, 9, 10, 3, 1])
array.sort()
print(array[::-1])

# 각 열을 기준으로 정렬
array = np.array([[5, 9, 10, 3, 1], [8, 3, 4, 2, 5]])
array.sort(axis=0)
print(array)

[ 1  3  5  9 10]
[10  9  5  3  1]
[[ 5  3  4  2  1]
 [ 8  9 10  3  5]]


Numpy 관련 자주 사용되는 함수는 다음과 같습니다.

In [6]:
import numpy as np

# 균일한 간격으로 데이터 생성
array = np.linspace(0, 10, 5)
print(array)

# 난수의 재연(실행마다 결과 동일)
np.random.seed(7)
print(np.random.randint(0, 10, (2, 3)))

# Numpy 배열 객체 복사
array1 = np.arange(0, 10)
array2 = array1.copy()
print(array2)

# 중복된 원소 제거
array = np.array([1, 1, 2, 3, 3, 3, 1])
print(np.unique(array))

[ 0.   2.5  5.   7.5 10. ]
[[4 9 6]
 [3 3 7]]
[0 1 2 3 4 5 6 7 8 9]
[1 2 3]
